image: docker:cli

stages:
  - build

variables:
  REGISTRY: ghcr.io
  IMAGE_NAME: $PROJECT_NAMESPACE/$PROJECT_NAME

before_script:
  - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD 

docker-build:
    stage: build
    only: 
        - schedules
    services:
        - docker:dind
    script:
        - docker build --pull -t "$IMAGE_NAME" .
        - docker tag "$IMAGE_NAME" "$REGISTRY/$IMAGE_NAME:main"
        - docker push "$REGISTRY/$IMAGE_NAME:main"
