version: '3.7'

services:
  caddy:
    image: ghcr.io/lukasw01/caddy-cloudflare:main
    restart: unless-stopped
    container_name: caddy
    networks:
      - web
    ports:
        - "80:80"
        - "443:443"
        - "2019:2019"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - ./data:/data
        - ./config:/config
        - ./logs:/var/log/
        - ./www:/usr/share/www
    labels:
      - io.containers.autoupdate=registry        


networks:
  web:
    external: true
